insert into Contacts (FirstName, LastName, Email, Phone, SubjectId, Message, CreatedAt)
values 
    ('Linh', 'Thùy', 'linhdao98@gmail.com', '', 1, 'Dear Sir, Is there any news regarding my order? Thanks', GETDATE()),
    ('Hồng', 'Ánh', 'hanh@gmail.com', '+122333666', 2, 'Dear Team, Is there any news regarding my request? Thanks', GETDATE()),
    ('Nguyễn', 'Văn A', 'nguyenvana@gmail.com', '', 3, 'Xin chào, Có thể đặt một bài viết không có sẵn trên trang web của bạn không? Cảm ơn', GETDATE()),
    ('Trần', 'Thị B', 'tranthib@gmail.com', '+122333666', 1, 'Kính gửi Quý khách hàng, Có thông tin gì về đơn hàng của tôi không? Cảm ơn', GETDATE()),
    ('Lê', 'Minh C', 'leminhc@gmail.com', '+123456789', 2, 'Chào bạn, Tôi có một yêu cầu đặc biệt, bạn có thể giúp được không? Cảm ơn', GETDATE()),
    ('Phạm', 'Hoàng D', 'phamhoangd@gmail.com', '', 3, 'Xin chào, Có thể tôi được tư vấn về sản phẩm của bạn không? Cảm ơn', GETDATE()),
    ('Nguyễn', 'Thị E', 'nguyenthie@gmail.com', '+987654321', 1, 'Kính gửi, Tôi muốn biết thêm về các dự án của bạn. Cảm ơn', GETDATE()),
    ('Trần', 'Mạnh F', 'tranmanhf@gmail.com', '', 2, 'Xin chào, Tôi muốn đặt hàng sản phẩm của bạn. Có sẵn không? Cảm ơn', GETDATE()),
    ('Lê', 'Như G', 'lenhug@gmail.com', '+111222333', 3, 'Kính gửi, Tôi cần hỗ trợ kỹ thuật. Có ai giúp được không? Cảm ơn', GETDATE()),
    ('Phạm', 'Thanh H', 'phamthanhh@gmail.com', '', 1, 'Xin chào, Tôi muốn đặt hàng một lô sản phẩm của bạn. Có thể gọi điện cho tôi không? Cảm ơn', GETDATE()),
    ('Võ', 'Hà I', 'vohai@gmail.com', '+555666777', 2, 'Kính gửi, Tôi muốn biết thêm về chương trình khuyến mãi của bạn. Cảm ơn', GETDATE()),
    ('Nguyễn', 'Văn K', 'nguyenvank@gmail.com', '', 3, 'Chào bạn, Tôi muốn mua sản phẩm của bạn. Làm ơn gửi thông tin chi tiết. Cảm ơn', GETDATE()),
    ('Trần', 'Thị L', 'tranthil@gmail.com', '+999888777', 1, 'Kính gửi, Tôi cần tư vấn về dự án của bạn. Cảm ơn', GETDATE()),
    ('Lê', 'Minh M', 'leminhm@gmail.com', '', 2, 'Xin chào, Tôi có thể hỏi một số câu hỏi về sản phẩm của bạn không? Cảm ơn', GETDATE()),
    ('Phạm', 'Hoàng N', 'phamhoangn@gmail.com', '', 3, 'Kính gửi, Tôi muốn biết thêm về dịch vụ của bạn. Cảm ơn', GETDATE()),
    ('Nguyễn', 'Thị P', 'nguyenthip@gmail.com', '', 1, 'Xin chào, Tôi có một dự án cần sự tư vấn. Có thể giúp không? Cảm ơn', GETDATE()),
    ('Trần', 'Mạnh Q', 'tranmanhq@gmail.com', '+777888999', 2, 'Kính gửi, Tôi muốn đặt hàng sản phẩm của bạn. Có sẵn không? Cảm ơn', GETDATE()),
    ('Lê', 'Như R', 'lenhur@gmail.com', '', 3, 'Xin chào, Tôi có thể mua sản phẩm của bạn trực tuyến không? Cảm ơn', GETDATE()),
    ('Phạm', 'Thanh S', 'phamthanhs@gmail.com', '+444555666', 1, 'Chào bạn, Tôi muốn mua sản phẩm của bạn. Có thể liên hệ lại với tôi không? Cảm ơn', GETDATE()),
    ('Võ', 'Hà T', 'vohat@gmail.com', '', 2, 'Kính gửi, Tôi cần một báo giá cho dự án của mình. Cảm ơn', GETDATE()),
    ('Nguyễn', 'Văn U', 'nguyenvanu@gmail.com', '', 3, 'Xin chào, Tôi muốn đặt hàng sản phẩm của bạn. Có thể giao hàng đến địa chỉ của tôi không? Cảm ơn', GETDATE()),
    ('Trần', 'Thị V', 'tranthiv@gmail.com', '+333222111', 1, 'Kính gửi, Tôi muốn biết thêm về chính sách đổi trả của bạn. Cảm ơn', GETDATE()),
    ('Lê', 'Minh X', 'leminhx@gmail.com', '', 2, 'Chào bạn, Tôi có thể đặt hàng trực tuyến không? Cảm ơn', GETDATE());
